### ISSUE TITLE
Attention is implemented incorrectly

### ISSUE THREAD

**Issue by 0b01** [sayondutta/text_summarizer#2]
This line:
https://github.com/sayondutta/text_summarizer/blob/master/Seq2Seq_model_for_TextSummarizer-600L.py#L239
```python
prev_out_with_weights = tf.matmul(previous_output, w['score'])
```

should be a multiplication between previous_state and w['score']

Could you please change that? Thanks in advance.

**Comment by 0b01** [comment]
Please ignore. It's correct.

Src: https://github.com/tensorflow/tensorflow/blob/7c10b24de3cb2408441dfd98e1a1a1e8f43f3a7d/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py#L348

**Comment by 0b01** [comment]
Actually it should be the output of the current cell (not previous_output)

https://github.com/tensorflow/tensorflow/blob/7c10b24de3cb2408441dfd98e1a1a1e8f43f3a7d/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py#L709

This raw_rnn function doesn't support it I see.

**Comment by 0b01** [comment]
Using previous_output is possible:
https://arxiv.org/pdf/1508.04025.pdf

Page 4

 On the other hand, at
any time t, Bahdanau et al. (2015) build from the
previous hidden state ht−1 → at → ct →
ht
, which, in turn, goes through a deep-output
and a maxout layer before making predictions.7
Lastly, Bahdanau et al. (2015) only experimented
with one alignment function, the concat product;
whereas we show later that the other alternatives
are better.

**Comment by sayondutta** [comment]
Ricky, can you share your Skype id. In case you can help me over a call.

**Comment by 0b01** [comment]
I have emailed you.

**Comment by sayondutta** [comment]
Thanks. Any other suggestion for improvement because the loss is not converging that much. Will batch_size and or change in word_embeddings approach help ?
